const data = {
    "name": "codeplayground",
    "version": "0.1.0",
    "private": true,
    "scripts": {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint",
      "prepare": "husky install",
      "pre-commit": "npm run lint",
    
      "buildNextApp": "set PUBLIC_URL=http:/nextApp.com/&&react-scripts --max_old_space_size=8192 build",
      "lints": "eslint --ext .js,.jsx ./src",
      "lint:fix": "eslint --fix --ext .js,.jsx ./src",
      "test": "jest",
      "test:ci": "jest --ci"
    },
    "dependencies": {
      "@next/font": "13.1.6",
      "@types/node": "18.13.0",
      "@types/react": "18.0.28",
      "@types/react-dom": "18.0.11",
      "eslint": "8.34.0",
      "eslint-config-next": "13.1.6",
      "next": "13.1.6",
      "react": "18.2.0",
      "react-dom": "18.2.0",
      "typescript": "4.9.5",
      "@ckeditor/ckeditor5-build-classic": "^37.1.0",
      "@ckeditor/ckeditor5-react": "^6.0.0",
      "@date-io/date-fns": "^2.14.0",
      "@emotion/react": "^11.4.1",
      "@emotion/styled": "^11.3.0",
      "@iconify/icons-ant-design": "^1.1.0",
      "@iconify/icons-eva": "^1.1.0",
      "@iconify/icons-ic": "^1.1.10",
      "@material-ui/core": "^4.12.4",
      "@mui/icons-material": "^5.6.2",
      "@mui/lab": "^5.0.0-alpha.47",
      "@mui/material": "^5.0.0",
      "@mui/utils": "^5.0.0",
      "@mui/x-data-grid": "^5.9.0",
      "@testing-library/jest-dom": "^5.14.1",
      "apexcharts": "^3.28.3",
      "babel-loader": "^8.1.0",
      "bootstrap": "^5.1.3",
      "change-case": "^4.1.2",
      "crypto-js": "^4.1.1",
      "d3-collection": "^1.0.7",
      "date-fns": "^2.24.0",
      "decorator-wrap": "^1.2.4",
      "faker": "^5.5.3",
      "formik": "^2.2.9",
      "framer-motion": "^4.1.17",
      "history": "^5.0.1",
      "lodash": "^4.17.21",
      "numeral": "^2.0.6",
      "prop-types": "^15.7.2",
      "react-alice-carousel": "^2.6.4",
      "react-apexcharts": "^1.3.9",
      "react-bootstrap": "^2.3.1",
      "react-copy-to-clipboard": "^5.1.0",
      "react-csv": "^2.2.2",
      "react-date-range": "^1.4.0",
      "react-excel-renderer": "^1.1.0",
      "react-file-viewer": "^1.2.1",
      "react-gauge-chart": "^0.4.1",
      "react-grid-layout": "^1.3.4",
      "react-helmet-async": "^1.1.2",
      "react-icons": "^4.3.1",
      "react-image-zoom-pan": "^0.3.1",
      "react-pdf": "^5.7.2",
      "react-router-dom": "^6.0.0-beta.4",
      "react-scripts": "^5.0.0",
      "react-signature-canvas": "^1.0.6",
      "react-to-print": "^2.14.11",
      "react-zoom-pan-pinch": "^2.6.1",
      "simplebar": "^5.3.5",
      "simplebar-react": "^2.3.5",
      "use-react-router-breadcrumbs": "^3.2.1",
      "video-react": "^0.15.0",
      "web-vitals": "^2.1.0",
      "yup": "^0.32.9",
      "react-docgen": "^5.4.0",
      "react-styleguidist": "^11.2.0",
      "wilster-doc": "^1.0.4",
        "@iconify/react": "^4.0.1",
        "@innovatrics/dot-document-auto-capture": "^3.5.2",
        "@innovatrics/dot-face-auto-capture": "^3.5.2",
        "@react-google-maps/api": "^2.17.1",
        "@reduxjs/toolkit": "^1.9.1",
        "@tanstack/react-query": "^4.20.4",
        "@tensorflow-models/face-landmarks-detection": "^1.0.2",
        "@tensorflow/tfjs": "^4.1.0",
        "@tensorflow/tfjs-backend-webgl": "^4.1.0",
        "@tensorflow/tfjs-converter": "^4.1.0",
        "@tensorflow/tfjs-core": "^4.1.0",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^14.4.3",
        "@trpc/client": "^10.7.0",
        "@trpc/next": "^10.7.0",
        "@trpc/react-query": "^10.7.0",
        "@trpc/server": "^10.7.0",
        "@typescript-eslint/eslint-plugin": "^5.48.0",
        "@typescript-eslint/parser": "^5.48.0",
        "@useweb/use-firebase": "^10.0.1",
        "airbnb": "^0.0.2",
        "babel-jest": "^29.3.1",
        "cytoscape": "^3.23.0",
        "cytoscape-context-menus": "^4.1.0",
        "cytoscape-cose-bilkent": "^4.1.0",
        "cytoscape-expand-collapse": "^4.1.0",
        "d3": "^7.8.0",
        "dayjs": "^1.11.7",
        "drawflow": "^0.0.59",
        "eslint-config-airbnb-typescript": "^17.0.0",
        "eslint-plugin-flow": "^2.29.1",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-next": "^0.0.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-react": "^7.31.11",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-testing-library": "^5.9.1",
        "face-api.js": "^0.22.2",
        "firebase": "^9.15.0",
        "highcharts": "^10.3.2",
        "highcharts-react-official": "^3.1.0",
        "html2canvas": "^1.4.1",
        "html5-qrcode": "^2.3.4",
        "i18next": "^22.4.6",
        "i18next-browser-languagedetector": "^7.0.1",
        "i18next-http-backend": "^2.1.1",
        "iconify": "^1.4.0",
        "identity-obj-proxy": "^3.0.0",
        "javascript-barcode-reader": "^0.6.9",
        "jest": "^29.3.1",
        "jspdf": "^2.5.1",
      
        "moment": "^2.29.4",
  
        "notistack": "^2.0.8",
      
        "prismjs": "^1.29.0",
      
        "quagga": "^0.12.1",
    
   
        "react-barcode": "^1.4.6",
        "react-beautiful-dnd": "^13.1.1",
        "react-collapsible": "^2.10.0",
   
        "react-cytoscapejs": "^2.0.0",
     
        "react-i18next": "^12.1.1",
        
        "react-image-crop": "^10.0.9",
        "react-json-view": "^1.21.3",
        "react-otp-input": "^2.4.0",
  
        "react-qr-barcode-scanner": "^1.0.6",
        "react-query": "^3.39.2",
        "react-querybuilder": "^5.3.3",
        "react-quill": "^2.0.0",
        "react-router": "^6.6.1",
        "react-simple-code-editor": "^0.13.1",
    
        "thaidatepicker-react": "^0.2.2",
        "topojson-client": "^3.1.0",
       
        "zod": "^3.20.2",
        "zustand": "^4.2.0"
    },
     
      "devDependencies": {
        "@babel/cli": "^7.20.7",
        "@babel/core": "^7.20.7",
        "@babel/preset-env": "^7.20.2",
        "@babel/preset-react": "^7.18.6",
        "@babel/preset-typescript": "^7.18.6",
        "@swc/core": "^1.3.24",
        "@types/node": "^18.11.18",
        "babel-loader": "^9.1.0",
        "eslint-config-prettier": "^8.6.0",
        "html-webpack-plugin": "^5.5.0",
        "husky": "^8.0.3",
        "prettier": "2.8.1",
        "swc-loader": "^0.2.3",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.5",
        "webpack": "^5.0.0-rc.6",
        "webpack-cli": "^5.0.1",
        "webpack-dev-server": "^4.11.1"
      }
    
    
  }
  